---
- name: Create New Disk
  hosts: target2
  become: yes
  become_method: sudo
  tasks:
  - name: Apt update
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
      state: present

  - name: Install LVM 2
    apt:
      name: lvm2
      state: present

  - name: Install Rescan-Bus
    apt:
      name: scsitools
      state: present

  - name: Scan Disks
    shell:
      "rescan-scsi-bus"
  - debug:
      msg: ""

  - name: Create Partition
    community.general.parted:
      device: /dev/sdb
      number: 1
      flags: [ lvm ]
      state: present

  - name: vgcreate
    lvg: 
      vg: vgdata
      pvs: /dev/sdb1
  
  - name: lvcreate
    lvol:
      vg: vgdata
      lv: dataone
      size: 100%FREE

  - name: create file system
    filesystem:
      fstype: ext4
      dev: /dev/vgdata/dataone

  - name: mount logical volume
    mount:
      name: /lvdata
      src: /dev/vgdata/dataone
      fstype: ext4
      state: mounted
      