---
- name: Apt Update
  hosts: target1
  become: yes
  become_method: sudo
  tasks:
  - name: Apt update
    apt:
      update_cache: true
      cache_valid_time: 3600
      force_apt_get: true
      state: present
      